name: Build & Deploy

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: string
        required: true
        default: 'dev'
      aws_account:
        description: 'AWS account id'
        type: string
        required: true
        default: '11111111111'
      aws_region:
        description: 'AWS region'
        type: string
        required: false
        default: 'eu-west-2'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
      aws_account:
        description: 'AWS account id'
        required: true
        default: '11111111111'
        type: choice
        options:
          - '11111111111'
          - '33333333333'
      aws_region:
        description: 'AWS region'
        required: false
        default: 'eu-west-2'
        type: string

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      actions: write
      statuses: write
    env:
      AWS_REGION: ${{ inputs.aws_region }}
      AWS_ACCOUNT: ${{ inputs.aws_account }}
      ENVIRONMENT: ${{ inputs.environment }}
    concurrency:
      group: deploy-${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          environment: ${{ inputs.environment }}
          aws-role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}

      - name: Build Application
        run: pnpm run build

      - name: Deploy to Environment
        run: pnpm run deploy:${{ inputs.environment }}

