name: Quality Checks

permissions:
  id-token: write
  contents: read

on:
  workflow_call:

jobs:
  Linting:
    name: 🧹 Linting & Formatting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          environment: 'linting'
          aws-role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}

      - name: Run format check
        run: pnpm run format:check

      - name: Run lint check
        run: pnpm run lint:check

  TypeChecks:
    name: 🔍 Type Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          environment: 'type-checks'
          aws-role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}

      - name: Run Static Typechecks
        run: pnpm run types:check

  UnitTests:
    name: 🧪 Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          environment: 'unit-tests'
          aws-role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}

      - name: Run Unit Tests
        run: pnpm run test:unit

  CDKTests:
    name: 🦺  CDK Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          environment: 'cdk-tests'
          aws-role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}

      - name: Build Lambdas
        run: pnpm run build

      - name: Run CDK Tests
        run: pnpm run test:cdk

  CDKSynth:
    name: 🔍 CDK Synth
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          environment: 'cdk-synth'
          aws-role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}

      - name: Build Lambdas
        run: pnpm run build

      - name: Run CDK Synth
        run: pnpm run cdk synth

  CheckovScan:
    name: 🔍 Checkov Scan
    runs-on: ubuntu-latest
    needs: CDKSynth
    timeout-minutes: 10
    steps:
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: cdk.out
          config_file: .checkov.yaml
          baseline: .checkov.baseline
