name: Test

on: [pull_request]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: 🧪 Test Code artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          environment: 'test'
          aws-role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}

      - name: Run Tests
        run: pnpm run test

